# Copyright (c) .NET Foundation and Contributors
# See LICENSE file in the project root for full license information.

# This workflow will periodically check .NET nanoFramework dependencies and updates them in the repository it's running.

name: Daily update dependencies

on:
  schedule:
  # Update At 00:00 UTC on Tuesday and Friday
  - cron:  '0 0 * * 2,5'
  repository_dispatch:
    types: update-dependencies

jobs:
  update-nuget-dependencies:
    name: Update dependencies
    uses: nanoframework/nf-tools/.github/workflows/update-dependencies.yml@main
    with:
      solutionsToCheck: 'nanoFramework.Aws.IoTCore.Devices.sln'
    secrets:
      githubAuth: ${{ secrets.NFBOT_GITHUB_ACTIONS }}
